name: RISC-V Toolchain and LLVM Installation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install sphinx==5.3.0
        sudo apt-get install -y ninja-build
        sudo apt-get install -y lsb-release wget software-properties-common gnupg
      shell: bash
    
    - name: Clone QEMU from GitLab
      run: |
        git clone https://gitlab.com/qemu-project/qemu.git
        cd qemu
        mkdir install
      shell: bash
      
    - name: Configure QEMU
      run: |
        ./configure --prefix=/mnt/c/Users/User/qemu/install --target-list=riscv64-linux-user
      working-directory: qemu
      shell: bash

    - name: Build QEMU
      run: |
        sudo make
        sudo make install
      working-directory: qemu
      shell: bash

    - name: Install Clang-17, LLDB-17, and LLD-17
      run: |
        sudo apt-get update
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get install -y clang-17 lldb-17 lld-17
      shell: bash
